version: '3.1'

services:

  zabbixdb:
    image: monitoringartist/zabbix-db-mariadb:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=zabbix
      - MARIADB_PASS=my_password

  zabbixserver:
    image: monitoringartist/dockbix-xxl:dev
    depends_on:
      - zabbixdb
    ports:
      - "80:80"
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZS_DBHost=zabbixdb
      - ZS_DBUser=zabbix
      - ZS_DBPassword=my_password
      - ZS_HistoryStorageURL=http://elasticsearch:9200
      - XXL_zapix=true
      - XXL_grapher=true

  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200

  kibana:
    image: kibana
    ports:
      - 5601:5601
